BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE posts';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_POST_NO';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -2289 THEN
			RAISE;
		END IF;
END;
/

CREATE SEQUENCE SEQ_POST_NO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE TABLE posts (
	post_no NUMBER PRIMARY KEY,
	user_id VARCHAR2(50) NOT NULL,
	title VARCHAR2(150) NOT NULL,
	content VARCHAR2(4000) NOT NULL,
	created_at DATE DEFAULT SYSDATE NOT NULL
);
