DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;
DROP SEQUENCE IF EXISTS SEQ_POST_NO;

CREATE TABLE users (
	user_id VARCHAR2(50) PRIMARY KEY,
	password VARCHAR2(255) NOT NULL,
	name VARCHAR2(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ip_address VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_POST_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE posts (
	post_no NUMBER PRIMARY KEY,
	user_id VARCHAR2(50) NOT NULL,
	title VARCHAR2(150) NOT NULL,
	content VARCHAR2(4000) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
